{% set name = "pydirectinput" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PyDirectInput-{{ version }}.tar.gz
  sha256: bebe65102c69208688402f9f4cbd2ae7afc174fd2123e156e178b1304e7f80a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - __win

test:
  imports:
    - pydirectinput
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/learncodebygaming/pydirectinput
  summary: Python mouse and keyboard input automation for Windows using Direct Input.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
